# Generated by Django 4.0 on 2022-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Employee', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Company',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='none', max_length=200, null=True, upload_to='profile_img'),
        ),
    ]
