# Generated by Django 4.0 on 2022-03-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=200, verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=200, verbose_name='Ingredient'),
        ),
    ]
