# Generated by Django 4.0 on 2022-03-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_name_alter_ingredients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(default='New entry', max_length=200, verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='report',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(default='New entry', max_length=200, verbose_name='Ingredient'),
        ),
    ]
