# Generated by Django 4.0 on 2022-03-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_ingredients_name_alter_report_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
