# Generated by Django 4.0 on 2022-03-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='description',
            new_name='discription',
        ),
    ]
